### ISSUE TITLE
Example currently broken?

### ISSUE THREAD

**Issue by nikgraf** [esy-ocaml/hello-reason#1]
I ran:

```
npm install -g esy
git clone git@github.com:esy-ocaml/esy-reason-project.git
esy install
esy build
```

It failed with:

```
# Unformatted Error Output:
# File "lib/Util.re", line 1:
# Error: The files /Users/nikgraf/.esy/3_________________________________________________________________/i/opam__slash__lwt-3.3.0-16ed962b/lib/lwt/lwt.cmi
#        and /Users/nikgraf/.esy/3_________________________________________________________________/i/opam__slash__lambda_term-1.13.0-469605ef/lib/lambda-term/lTerm.cmi
#        make inconsistent assumptions over interface Lwt


 ERROR  lib/Util.re:1 0-0 

1 ┆ open Lwt;
2 ┆ 
3 ┆ open LTerm_style;
4 ┆ 
```

**Comment by nikgraf** [comment]
I tried upgrading this one to 4.0.0 https://github.com/esy-ocaml/esy-reason-project/blob/master/package.json#L26, but didn't help.

**Comment by andreypopp** [comment]
What version of esy did you use? Just tried on macOS with `esy@0.1.27` and no `esy.lock` and it succeeded.

**Comment by nikgraf** [comment]
If you run `npm install -g esy` it will fetch 0.70.0. Seems like the `@preview` version is more stable at this point than the `@latest` version. Does it make sense to update the docs on the website and recommend `npm install -g esy@preview` or cut a `@latest` release?

What I want to fix is the beginner story and currently this flow is broken: https://esy.sh/docs/en/getting-started.html

**Comment by andreypopp** [comment]
This is fixed.
