### ISSUE TITLE
"bash: parse_git_branch: command not found" on build

### ISSUE THREAD

**Issue by blairwilcox** [esy-ocaml/hello-reason#12]
I've installed esy, but when I try to run `esy build` I get the following error:

```
bash: parse_git_branch: command not found
```

I'm currently on MacOS 10.14.1. Any idea what might be causing this?

**Comment by jordwalke** [comment]
Maybe it's related to how you setup bashrc/bash profile? https://stackoverflow.com/questions/47212149/getting-error-bash-parse-git-branch-command-not-found
Esy runs build commands in a constrained bash shell that doesn't have everything inherited from your main shell.

**Comment by andreypopp** [comment]
In fact `esy` shouldn't inherit env at all from the parent shell. Can you run `esy build-env --json` and see if it contains references to `parse_git_branch`? Does `esy build env` works? Does it contain references to `parse_git_branch` too?

**Comment by blairwilcox** [comment]
Yeah, I think what happened was that I was having issues at another step and tried to run `sudo esy`. Running `sudo -k` fixed the issue and everything built normally. The problem was on my end, I'll close the ticket. Thanks for all your help!
