### ISSUE TITLE
Generate docs with odoc

### ISSUE THREAD

**Issue by rizo** [esy-ocaml/hello-reason#13]
Dune provides builtin support for documentation generation with `odoc`. Generating Reason syntax with `odoc` is already possible. This means that we can generate documentation for any Reason+esy project!

There're some things that need to be fixed first, in particular:

- [ ] Unattached docstring parsing currently seems to be broken in the Reason parser. (I'll open a separate issue for this later.)
- [x] Currently odoc generates OCaml syntax by default. We need to teach dune how to generate Reason syntax for docs (https://github.com/ocaml/odoc/issues/129).
  * This could be done by setting an environment variable
  * Or by generating Reason syntax for `rei` files
- [x] The generated docs are currently placed in the `_build/default/_doc/_html` directory inside esy's environment. I think asking users to go to that directory to open docs is not ideal.

I already started working on this and expect to have something functional soon.

CC @jordwalke @aantron

**Comment by andreypopp** [comment]
Thanks for looking into this! I've tried odoc with some of my esy-based projects and I really liked how it looks!

> The generated docs are currently placed in the _build/default/_doc/_html directory inside esy's environment. I think asking users to go to that directory to open docs is not ideal.

In the next esy version it would be possible to reference esy envs from a command line like this:
```
% esy x '#{self.doc}/_html/index.html'
```
I think we can add a script `esy opendoc` which does that.

**Comment by rizo** [comment]
> I think we can add a script esy opendoc which does that.

That would be great!

**Comment by jordwalke** [comment]
>  Unattached docstring parsing currently seems to be broken in the Reason parser. (I'll open a separate issue for this later.)


Did you try this:

```
/**
 * Unattached doc string.
 */;
```

Note the semicolon.

**Comment by jordwalke** [comment]
In the mean time they can setup an `esy opendoc` command by doing:
```
"scripts": {
   "opendoc": "open #{self.target_dir/'_doc'/'_html'/'index.html'}"
}
```

**Comment by rizo** [comment]
@jordwalke I forgot about that workaround. Or is it not a workaround? :)

Regarding `open`: it's not portable across operating systems, maybe there's a better way to do that.

**Comment by jordwalke** [comment]
> Regarding open: it's not portable across operating systems, maybe there's a better way to do that.

There's an opam package for that! (Probably overkill to take on a dependency though.

**Comment by rizo** [comment]
I think this is done now. Or at least current master is in a good enough shape IMO.
