### ISSUE TITLE
Error on esy install

### ISSUE THREAD

**Issue by harsh-vardhhan** [esy-ocaml/hello-reason#8]
on **esy install** of a freshly cloned copy says -
```
Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
in node_modules/esy/bin/esy-install.js
```
Any idea what could be the cause ?

**Comment by andreypopp** [comment]
What esy version you have installed? JS implementation of `esy install` was removed and replaced with a native implementation.

Try this:
```
% npm remove -g esy
% npm install -g esy
```
to get to the latest version.

**Comment by harsh-vardhhan** [comment]
Didn't check the version before installing but upgrading to the latest version worked.
